module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.16

replace k8s.io/klog => github.com/simonpasquier/klog-gokit v0.3.0

replace k8s.io/klog/v2 => github.com/simonpasquier/klog-gokit/v2 v2.1.0

require github.com/prometheus/prometheus v1.8.2-0.20210701133801-b0944590a1c9 // cmd/promtool
